version: 2

models:
  - name: product_analysis
    description: |
      Агрегированная витрина по товарным категориям.
      Содержит ключевые метрики: количество товаров, среднюю цену и общую стоимость товаров в разрезе категорий.
      Предназначена для анализа ассортимента и ценовой политики.

      **Источник данных:**
      - `stg_products` - очищенная модель сырых данных о товарах.

      **Бизнес-логика:**
      - Группировка по товарным категориям.
      - Расчет стандартных агрегатов (COUNT, AVG, SUM).

    # Метаданные переносим в корень конфигурации модели
    meta:
      owner: "Аналитический отдел"
      maturity: "development"

    config:
      tags: ["marts", "analysis"]  # Добавляем теги для удобства фильтрации

    columns:
      - name: product_category
        description: "Наименование категории товара. Группирующее поле для агрегации."

      - name: product_count
        description: "Количество товаров (SKU) в данной категории. Рассчитывается как COUNT(*)."

      - name: avg_price
        description: |
          Средняя цена товара в категории.
          **Внимание:** Рассчитана как простое среднее арифметическое (AVG).
          Может быть искажена наличием товаров-выбросов с очень высокой или низкой ценой.

      - name: total_value
        description: "Общая стоимость всех товаров в категории при их текущей цене. Рассчитана как SUM(product_price)."